set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/socs/intel/socgen/esp/esp_global.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/socs/intel/socketgen/sld_devices.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/socs/intel/socketgen/allacc.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/socs/intel/socketgen/genacc.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/socs/intel/socketgen/allcaches.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/misc/stdlib/version.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/misc/stdlib/config_types.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/misc/stdlib/config.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/misc/stdlib/stdlib.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/gencomp.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/allclkgen.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/alldco.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/allddr.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/allmem.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/allpll.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/allmul.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/bus/amba.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/bus/devices.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/cores/leon3/sparc.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/misc/misc.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sim/utils/stdio.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sim/utils/testlib.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sim/utils/sim.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sim/utils/sparc_disas.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sim/utils/cpu_disas.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sim/tb/tb_pkg.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/cores/leon3/multlib.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/cores/leon3/coretypes.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/cores/leon3/sldfpu/basic.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/cores/leon3/sldfpu/bw.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/cores/leon3/sldfpu/itsqrdiv.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/cores/leon3/sldfpu/sldfpp.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/cores/leon3/arith.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/cores/leon3/leon3.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/cores/leon3/mmuconfig.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/cores/leon3/mmuiface.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/cores/leon3/libmmu.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/cores/leon3/libfpu.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/cores/leon3/libiu.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/cores/leon3/libcache.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/cores/leon3/libleon3.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/cores/ibex/ibex_esp_pkg.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane_esp_pkg.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/proxy/esp_acc_regmap.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/monitor/monitor_pkg.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/csr/esp_csr_pkg.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/csr/esp_noc_csr_pkg.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/allpads.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/noc/genram_pkg.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/noc/nocpackage.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/caches/cachepackage.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/caches/gencaches.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/dvfs/dvfs.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/proxy/tile.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/jtag/jtag_pkg.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/ethernet/ethcomp.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/uart/uart.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/uart/libdcom.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/video/svga_pkg.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/timer/gptimer_pkg.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/ddr/ahb2mig_7series_pkg.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/ethernet/net.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/ethernet/ethernet_mac.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/ethernet/greth_pkg.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/socs/intel/socgen/grlib/grlib_config.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/socs/intel/socgen/esp/socmap.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/socs/intel/socketgen/sldacc.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/tiles/tiles_pkg.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/tiles/asic/tiles_asic_pkg.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/tiles/fpga/tiles_fpga_pkg.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/syncrambw.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/outpad_ds.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/pll.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/iopad_tm.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/iopad_ds.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/memrwcol.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/ddr_ireg.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/syncram64.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/clkmux.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/syncram_dp.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/inpad_ds.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/dco.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/syncram_2p.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/clkgen.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/iopad_ddr.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/inpad.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/outpad_ddr.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/outpad.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/clkpad.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/syncreg.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/ddr_oreg.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/clkand.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/syncram.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/iopad.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/inpad_ddr.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/clkpad_ds.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/regfile_3p.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/techmult.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/grgates.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/inferred/mul_inferred.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/inferred/ddr_inferred.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/inferred/memory_inferred.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/inferred/fifo_inferred.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/ethernet/greth_rx.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/ethernet/greth_tx.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/ethernet/eth_ahb_mst.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/ethernet/grethm.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/ethernet/greth.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/ethernet/grethc.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/ethernet/eth_edcl_ahb_mst.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/ethernet/eth_rstgen.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/timer/gptimer.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/uart/dcom.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/uart/apbuart.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/video/svgactrl.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/video/svga2tfp410.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/interrupt/irqmp.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/ddr/ahb2mig_7series.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/ddr/ahb2mig_7series_profpga.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/ddr/ahb2mig_up.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/ddr/ahb2mig_ebddr4r5.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/peripherals/ddr/ahb2bsg_dmc.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/caches/l2_wrapper.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/caches/llc_wrapper.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/caches/l2_acc_wrapper.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/caches/fifo_custom.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/misc/ahbram.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/misc/unread.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/misc/ahbslm.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/misc/esp_init.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/misc/ahbram_dp.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/misc/rstgen.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/noc/sync_noc_set.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/noc/noc32_xy.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/noc/fifo.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/noc/fifo2.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/noc/sync_noc_xy.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/noc/inferred_async_fifo.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/noc/noc32_synchronizers.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/noc/fifo3.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/noc/fifo1.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/noc/sync_noc32_xy.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/noc/router.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/proxy/noc2apb.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/proxy/noc2intreq.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/proxy/intreq2noc.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/proxy/ahbslv2noc.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/proxy/gp_arbiter.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/proxy/esp_acc_dma.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/proxy/apb2noc.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/proxy/ext2ahbm.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/proxy/iolink2ahbm.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/proxy/ahbslv2iolink.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/proxy/esp_acc_tlb.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/proxy/noc2ahbmst.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/proxy/fixen_64to32.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/proxy/intack2noc.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/proxy/mem2ext.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/proxy/axislv2noc.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/adapters/ahb2axi_l.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/queues/slm_tile_q.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/queues/acc_tile_q.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/queues/cpu_tile_q.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/queues/mem_tile_q.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/queues/empty_tile_q.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/queues/misc_tile_q.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/csr/esp_tile_csr.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/csr/esp_noc_csr.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/monitor/monitor.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/jtag/mux_6to1.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/jtag/demux_1to6.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/jtag/demux_1to2.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/jtag/demux_1to6_vs.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/jtag/counter_jtag.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/jtag/jtag_test.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/jtag/piso_jtag.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/jtag/sipo_jtag.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/jtag/jtag2apb.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/jtag/apb2jtag.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/jtag/jtag2apb_reg.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/jtag/apb2jtag_reg.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/jtag/jtag_apb_config.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/jtag/jtag_apb_slv_config.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/jtag/jtag_apb_slv.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/jtag/fpga_proxy_jtag.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/jtag/jtag_tb.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/dvfs/dvfs_top.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/dvfs/dvfs_fsm.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/dvfs/pm2noc.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/dvfs/token_pm.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/bus/patient_apbctrl.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/bus/ahbmst.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/bus/ahbtrace_mb.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/bus/ahbtrace_mmb.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/bus/ahbtrace.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/bus/ahbctrl.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/muxes/noc5_mux.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/sockets/sockets/noc_domain_socket.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/tiles/tile_empty.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/tiles/tile_slm.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/tiles/tile_mem.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/tiles/tile_cpu.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/tiles/tile_io.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/tiles/asic/asic_tile_acc.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/tiles/asic/asic_tile_cpu.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/tiles/asic/asic_tile_empty.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/tiles/asic/asic_tile_io.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/tiles/asic/asic_tile_mem.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/tiles/asic/asic_tile_slm.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/tiles/asic/asic_tile_slm_ddr.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/tiles/fpga/fpga_tile_acc.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/tiles/fpga/fpga_tile_cpu.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/tiles/fpga/fpga_tile_empty.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/tiles/fpga/fpga_tile_io.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/tiles/fpga/fpga_tile_mem.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/tiles/fpga/fpga_tile_slm.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/tiles/esp.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane_axi_wrap.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/riscv_plic_apb_wrap.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/riscv_clint_ahb_wrap.vhd
#set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/buffer_unisim.vhd
#set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/clkgen_unisim.vhd
#set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/ddr_unisim.vhd
#set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/memory_unisim.vhd
#set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/mul_unisim.vhd
#set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/pads_unisim.vhd
#set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/sgmii_vc707.vhd
#set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/sgmii_vcu118.vhd
#set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/sgmii_vcu118_clock_reset.vhd
#set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/spictrl_unisim.vhd
#set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/sysmon_unisim.vhd
#set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/tap_unisim.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/socs/intel/socketgen/accelerators.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/socs/intel/socketgen/caches.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/socs/intel/socketgen/noc_NV_NVDLA.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/socs/intel/socketgen/tile_acc.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/socs/intel/quartus/top.vhd
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/llc/rtl/llc_bufs.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/llc/rtl/llc_regs.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/llc/rtl/llc_interfaces.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/llc/rtl/llc_interface_defs.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/llc/rtl/llc_lookup_way.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/llc/rtl/pri_enc_half.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/llc/rtl/llc_localmem.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/llc/rtl/llc_localmem_asic.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/llc/rtl/llc_update.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/llc/rtl/llc_rtl_top.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/llc/rtl/pri_enc.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/llc/rtl/llc_process_request.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/llc/rtl/llc_core.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/llc/rtl/llc_input_decoder.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/l2/rtl/l2_fsm.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/l2/rtl/l2_bufs.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/l2/rtl/l2_interface_defs.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/l2/rtl/l2_write_word.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/l2/rtl/l2_rtl_top.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/l2/rtl/l2_interfaces.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/l2/rtl/l2_lookup.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/l2/rtl/l2_localmem.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/l2/rtl/l2_localmem_asic.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/l2/rtl/l2_regs.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/l2/rtl/l2_reqs.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/l2/rtl/l2_core.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/l2/rtl/l2_input_decoder.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/caches/esp-caches/common/rtl/interface_controller.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/misc/esplink.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/sockets/adapters/apb2axil.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/noc/router/noc_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/noc/router/router_fifo.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/noc/router/router_arbiter.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/noc/router/lookahead_routing.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/noc/router/lookahead_routing_multicast.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/noc/router/lookahead_router.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/noc/router/lookahead_router_multicast.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/noc/router/lookahead_router_wrapper.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/techmap/maps/clkdiv1234.v
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane_soc_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/include/riscv_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/riscv-dbg/src/dm_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/register_interface/src/reg_intf_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/include/ariane_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi/src/axi_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/include/ariane_axi_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/include/std_cache_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/include/wt_cache_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane_wrap.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/riscv_clint_wrap.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/riscv_plic_wrap.sv
#set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/mem/BRAM_1024x16.v
#set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/mem/BRAM_16384x1.v
#set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/mem/BRAM_2048x8.v
#set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/mem/BRAM_4096x4.v
#set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/mem/BRAM_512x32.v
#set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/mem/BRAM_8192x2.v
#set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/sgmii_vcu118_reset_sync.v
#set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/sram_b/unisim_sram_b_10abits.v
#set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/sram_b/unisim_sram_b_11abits.v
#set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/sram_b/unisim_sram_b_12abits.v
#set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/sram_b/unisim_sram_b_13abits.v
#set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/sram_b/unisim_sram_b_14abits.v
#set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/sram_b/unisim_sram_b_15abits.v
#set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/sram_b/unisim_sram_b_16abits.v
#set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/sram_b/unisim_sram_b_17abits.v
#set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/sram_b/unisim_sram_b_18abits.v
#set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/sram_b/unisim_sram_b_19abits.v
#set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/sram_b/unisim_sram_b_20abits.v
#set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/sram_b/unisim_sram_b_6abits.v
#set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/sram_b/unisim_sram_b_7abits.v
#set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/sram_b/unisim_sram_b_8abits.v
#set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/techmap/virtex7/sram_b/unisim_sram_b_9abits.v
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/register_interface/src/reg_intf.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/register_interface/src/apb_to_reg.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/include/axi_intf.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/include/instr_tracer_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/serdiv.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/ariane_regfile_ff.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/issue_stage.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/id_stage.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/branch_unit.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/controller.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/commit_stage.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/re_name.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/ariane.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/csr_buffer.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/tlb.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/decoder.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/ex_stage.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/scoreboard.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/mmu.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/store_unit.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_adapter.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/fpu_wrap.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/load_store_unit.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/ptw.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/multiplier.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/store_buffer.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/compressed_decoder.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_shim.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/alu.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/instr_realign.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/perf_counters.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/amo_buffer.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/mult.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/csr_regfile.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/load_unit.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/issue_read_operands.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_fma.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_opgroup_fmt_slice.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_divsqrt_multi.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_fma_multi.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_opgroup_multifmt_slice.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_classifier.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_noncomp.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_cast_multi.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_opgroup_block.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_rounding.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_top.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/control_mvp.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_mvp_wrapper.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/frontend/frontend.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/frontend/instr_scan.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/frontend/instr_queue.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/frontend/bht.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/frontend/btb.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/frontend/ras.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/cache_subsystem/tag_cmp.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/cache_subsystem/cache_ctrl.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/cache_subsystem/amo_alu.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/cache_subsystem/wt_axi_adapter.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/cache_subsystem/std_nbdcache.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/cache_subsystem/wt_dcache_ctrl.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/cache_subsystem/miss_handler.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/cache_subsystem/wt_cache_subsystem.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/cache_subsystem/wt_dcache_missunit.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/cache_subsystem/wt_icache.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/cache_subsystem/std_icache.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/cache_subsystem/wt_dcache_wbuffer.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/cache_subsystem/wt_l15_adapter.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/cache_subsystem/wt_dcache_mem.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/cache_subsystem/std_cache_subsystem.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/cache_subsystem/wt_dcache_inval.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/cache_subsystem/wt_dcache.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/clint/axi_lite_interface.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/clint/clint.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/fpga/src/axi2apb/src/axi2apb_wrap.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/fpga/src/axi2apb/src/axi2apb.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/fpga/src/axi2apb/src/axi2apb_64_32.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/fpga/src/axi_slice/src/axi_w_buffer.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/fpga/src/axi_slice/src/axi_r_buffer.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/fpga/src/axi_slice/src/axi_slice_wrap.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/fpga/src/axi_slice/src/axi_slice.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/fpga/src/axi_slice/src/axi_single_slice.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/fpga/src/axi_slice/src/axi_ar_buffer.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/fpga/src/axi_slice/src/axi_b_buffer.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/fpga/src/axi_slice/src/axi_aw_buffer.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_node/src/axi_regs_top.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_node/src/axi_BR_allocator.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_node/src/axi_BW_allocator.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_node/src/axi_address_decoder_BR.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_node/src/axi_DW_allocator.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_node/src/axi_address_decoder_BW.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_node/src/axi_address_decoder_DW.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_node/src/axi_node_arbiter.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_node/src/axi_response_block.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_node/src/axi_request_block.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_node/src/axi_AR_allocator.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_node/src/axi_AW_allocator.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_node/src/axi_address_decoder_AR.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_node/src/axi_address_decoder_AW.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_node/src/apb_regs_top.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_node/src/axi_node_intf_wrap.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_node/src/axi_node.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_node/src/axi_node_wrap_with_slices.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_node/src/axi_multiplexer.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_riscv_atomics/src/axi_riscv_amos.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_riscv_atomics/src/axi_riscv_atomics.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_riscv_atomics/src/axi_res_tbl.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_riscv_atomics/src/axi_riscv_lrsc_wrap.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_riscv_atomics/src/axi_riscv_amos_alu.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_riscv_atomics/src/axi_riscv_lrsc.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_riscv_atomics/src/axi_riscv_atomics_wrap.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi_mem_if/src/axi2mem.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/rv_plic/rtl/rv_plic_target.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/rv_plic/rtl/rv_plic_gateway.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/rv_plic/rtl/plic_top.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/riscv-dbg/src/dmi_jtag.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/riscv-dbg/src/dmi_jtag_tap.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/riscv-dbg/src/dm_csrs.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/riscv-dbg/src/dm_mem.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/riscv-dbg/src/dm_sba.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/riscv-dbg/src/dm_top.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/riscv-dbg/debug_rom/debug_rom.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi/src/axi_intf_bind_mst.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi/src/axi_intf_bind_slv.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi/src/axi_multicut.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/deprecated/pulp_sync.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/deprecated/find_first_one.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/stream_mux.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/stream_demux.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/exp_backoff.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/util/axi_master_connect.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/util/axi_slave_connect.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/util/axi_master_connect_rev.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/util/axi_slave_connect_rev.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/util/ex_trace_item.svh
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/util/instr_trace_item.svh
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/util/instr_tracer_if.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/util/instr_tracer.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/util/sram.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi/src/axi_cut.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi/src/axi_join.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi/src/axi_delayer.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/axi/src/axi_to_axi_lite.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/sync.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/spill_register.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/sync_wedge.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/edge_detect.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/stream_arbiter.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/stream_arbiter_flushable.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/deprecated/fifo_v1.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/deprecated/fifo_v2.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/fifo_v3.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/lzc.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/popcount.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/rr_arb_tree.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/deprecated/rrarbiter.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/stream_delay.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/lfsr_8bit.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/lfsr_16bit.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/counter.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/shift_reg.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/common_cells/src/sram.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/tech_cells_generic/src/pulp_clock_gating.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/tech_cells_generic/src/cluster_clock_inverter.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/tech_cells_generic/src/pulp_clock_mux2.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/socs/intel/socgen/esp/plic_regmap.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ariane/ariane/src/fpga-support/rtl/SyncSpRamBeNx64.sv

### Added one ####
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/altera_mf/clkgen_altera_mf.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/altera_mf/memory_altera_mf.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/altera_mf/tap_altera_mf.vhd
set_global_assignment -name VHDL_FILE /home/yaagna/intel_esp/esp/rtl/techmap/altera_mf/clkgen_stratix10.vhd
