set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ibex/ibex/rtl/ibex_core.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ibex/ibex/rtl/ibex_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ibex/ibex/rtl/ibex_alu.sv'
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ibex/ibex/rtl/ibex_compressed_decoder.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ibex/ibex/rtl/ibex_controller.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ibex/ibex/rtl/ibex_counter.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ibex/ibex/rtl/ibex_cs_registers.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ibex/ibex/rtl/ibex_decoder.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ibex/ibex/rtl/ibex_ex_block.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ibex/ibex/rtl/ibex_id_stage.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ibex/ibex/rtl/ibex_if_stage.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ibex/ibex/rtl/ibex_load_store_unit.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ibex/ibex/rtl/ibex_multdiv_slow.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ibex/ibex/rtl/ibex_multdiv_fast.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ibex/ibex/rtl/ibex_prefetch_buffer.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ibex/ibex/rtl/ibex_fetch_fifo.sv
set_global_assignment -name SYSTEMVERILOG_FILE /home/yaagna/intel_esp/esp/rtl/cores/ibex/ibex/rtl/ibex_register_file_ff.sv
#quartus_sh --flow compile ibex_prefetch_buffer
#set_global_assignment -name DEMOTE_ERROR_TO_WARNING 13411
#set_global_assignment -name SUPPRESS 13411
